### ISSUE TITLE
Segfault on library sync

### ISSUE THREAD

**Issue by TheGag96** [alainm23/byte#93]
Hi. I installed this player and tried to run it, but I get a segfault towards the end of syncing with my library. Doing a backtrace in GDB on the crash yielded this:

```
Thread 1 "com.github.alai" received signal SIGSEGV, Segmentation fault.
0x00007ffff4c64e50 in taglib_file_audioproperties () from /usr/lib/x86_64-linux-gnu/libtag_c.so.0
(gdb) bt
#0  0x00007ffff4c64e50 in taglib_file_audioproperties () at /usr/lib/x86_64-linux-gnu/libtag_c.so.0
#1  0x00005555555723e3 in  ()
#2  0x00007ffff75f1285 in g_main_context_dispatch () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007ffff75f1650 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007ffff75f16dc in g_main_context_iteration () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007ffff701aefd in g_application_run () at /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#6  0x0000555555563f03 in  ()
#7  0x00007ffff4893b97 in __libc_start_main (main=
    0x555555562d20, argc=1, argv=0x7fffffffe218, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffe208) at ../csu/libc-start.c:310
#8  0x0000555555562d5a in  ()
```

Hopefully this helps!

**Comment by jaimiewashere** [comment]
If I'm not being wrong, I think this issue is the same as #17 !
The back-trace may be useful though!
